---
- name: PLAY 1 - ISSUE SNMP COMMANDS
  hosts: iosxe
  connection: local
  gather_facts: no

  tasks:
    - name: TASK1 - DEPLOY SNMP COMMANDS
      ios_command:
        commands:
          - show run | inc snmp
        provider:
          username: cisco
          password: cisco
          host: "{{ inventory_hostname }}"

    - name: TASK 2- DEPLOY SNMP COMMANDS
      ios_config:
        commands:
          - snmp-server community private RW
        provider:
          username: cisco
          password: cisco
          host: "{{ inventory_hostname }}"
